version: '3'
services:
  postgres:
    image: postgres
    container_name: aha_postgres
    restart: always
    environment:
      POSTGRES_USER: nlnl
      POSTGRES_PASSWORD: nlnl
      POSTGRES_DB: nlnl
      TZ: Asia/Taipei
    ports:
      - 45432:5432
    volumes:
      - ./docker/bin/postgres/:/docker-entrypoint-initdb.d/
      - ./docker/data/postgresql/:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: aha_redis
    restart: always
    ports:
      - '46379:6379'
    privileged: true
